### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by zaidshakil** [pavelrevak/pystlink#4]
Traceback (most recent call last):
  File "pystlink.py", line 4, in <module>
    import lib.stlinkusb
  File "/home/zaidshakil/TU Berlin/Robotics/pystlink/lib/stlinkusb.py", line 1, in <module>
    import usb.core
ImportError: No module named 'usb'

i keep getting this error, please suggest. I have updated the firmware

**Comment by pavelrevak** [comment]
Hello zadshakil, you don't have installed pyusb and libusb
https://github.com/pavelrevak/pystlink/blob/master/README.md#requirements

**Comment by zaidshakil** [comment]
Thank you for replying. 
I have those 2 installed.

**Comment by pavelrevak** [comment]
then pyusb is probably installed for different version of python

try run: `python3` and inside type `import usb.core` to test if is installed correctly.

**Comment by jimfred** [comment]
I had a similar issue, was seeing 'ImportError: No module named usb.core' when running 'pystlink_test.py' from the Windows command line. When running 'python pystlink_test.py', it ran successfully.
